version: "3.9"
services:
  eureka:
    build:  /eureka-server
    ports:
      - "8761:8761"
    image: "eureka-server"
  user_service:
    build: ../../user_service
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8084:8084"
    image: "user_service"
 order_service:
    build: ../../order_service
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8085:8085"
    image: "order_service"
  gateway:
    build: /api-gateway-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8888:8888"
    image: "api-gateway-server"