
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      
      routes:
      - id: user-service
        uri: http://localhost:8084
        predicates:
        - Path=/api/user/**
        
      - id: order-service
        uri: http://localhost:8085
        predicates:
        - Path=/api/order/**
 
        

    